#!/usr/bin/env Rscript

## Copyright (C) 2022 Julien Dorier and UNIL (University of Lausanne).
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or (at
## your option) any later version.
##
## This program is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
## General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program. If not, see <https://www.gnu.org/licenses/>.

##########################################
#parse command line options
##########################################
          
args=commandArgs(trailingOnly = TRUE)

library(optparse)

usage="
  %prog [options] tissue_segmentation_RData"

description="
Positional arguments:
\ttissue_segmentation_RData
\t\tRData file generated by tissue_segmentation.R."

epilogue=""

#default=NA => mandatory, default=NULL => optional.
option_list=list( 
    make_option(c("--nprocesses"), type="integer", default=1,metavar="N",
                help="Max number of threads to use (only for data.table) [default %default]."),
    make_option(c("--excluded-regions"), type="character", default=NULL,metavar="FILENAME",
                help="File with excluded regions (closed polygons).
\t\tComma separated format with header in the first row and 3 columns: id, x and y.
\t\tThis file can contain multiple polygons, each with a different id.
\t\tPolygons are assumed to be closed, i.e. last point will be connected to first point.
\t\tAll cells with center inside an excluded region will be ignored."),
    make_option(c("--output"), type="character", default=NA,metavar="FILENAME",
                help="Output file (.tsv tab separated format) [mandatory].")
)


opt=parse_args(OptionParser(option_list=option_list,
                            usage=usage,
                            description=description,
                            epilogue=epilogue
                            ),positional_arguments=1,args=args)

##check all options are set, and print them
for(o in option_list)
{
    n=slot(o,"dest")
    f=c(slot(o,"short_flag"),slot(o,"long_flag"))
    f=paste(f[!is.na(f)],sep=",")
    if(!is.null(opt$options[[n]])) ##Default NULL => optional.
    {
        if(is.na(opt$options[[n]])) ##Default NA => mandatory
            stop("option ",f," is mandatory")
        ##check type
        if(typeof(opt$options[[n]])!=slot(o,"type"))
            stop("option ",f," must be ",slot(o,"type"))
        ##print
        if(slot(o,"action")!="store_true")
            cat(slot(o,"long_flag"),"=",opt$options[[n]],"\n",sep="")
        if(slot(o,"action")=="store_true"&&opt$options[[n]]==TRUE)
            cat(slot(o,"long_flag"),"\n",sep="")
    }
}
cat("positional arguments: ",paste(opt$args,collapse=" "),"\n",sep="")

nprocesses=opt$options[["nprocesses"]]
input.excluded.regions=opt$options[["excluded-regions"]]
outputfile=opt$options[["output"]]


##check
if(!(is.finite(nprocesses)&nprocesses>0))
{
    stop("--nprocesses must be a positive integer")
}

##positional arguments
input.RData=opt$args[1]



dir.create(dirname(outputfile),showWarnings=FALSE,recursive=TRUE)

library(data.table)
library(sp) #point.in.polygon

#nb threads for data.table
setDTthreads(nprocesses)

############################################
##load
############################################

cat(paste0("[",format(Sys.time()),"] "),"loading",input.RData,"\n")
load(input.RData)

############################################
##load excluded region
############################################

excluded.regions=data.table(id=integer(0))
if(!is.null(input.excluded.regions))
{
    cat(paste0("[",format(Sys.time()),"] "),"reading",input.excluded.regions,"\n")
    excluded.regions=fread(input.excluded.regions)
}

############################################
## flag cells to filter out 
############################################

voronoi.cells.summary[,excluded:=FALSE]
if(!is.null(input.excluded.regions))
{
    ##exclude points
    for(i in excluded.regions[,unique(id)])
        voronoi.cells.summary$excluded=voronoi.cells.summary$excluded|(point.in.polygon(voronoi.cells.summary$nucleus.x,voronoi.cells.summary$nucleus.y,excluded.regions[id==i,x],excluded.regions[id==i,y])!=0)

}

############################################
##save tissue area
############################################
tissue.area.tmp=voronoi.cells.summary[excluded==FALSE,.(tissue.area.pixel2=round(sum(area)),tissue.area.micron2=round(convert.image.to.slide.area(sum(area),image.info))),by=tissue.type][data.table(tissue.type=c("tumor","stroma","other")),on="tissue.type"]
tissue.area.tmp[is.na(tissue.area.pixel2),tissue.area.pixel2:=0]
tissue.area.tmp[is.na(tissue.area.micron2),tissue.area.micron2:=0]

cat(paste0("[",format(Sys.time()),"] "),"Saving results in",outputfile,"\n")
write.table(tissue.area.tmp,file=outputfile,sep="\t",quote=FALSE,row.names=FALSE,col.names=TRUE)

cat(paste0("[",format(Sys.time()),"] "),"Done\n")
